
#
# Configuration file for Travis CI
# http://travis-ci.org/
#

language: java

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8


before_install:
  - git clone https://github.com/Wikidata/Wikidata-Toolkit.git
  - cd Wikidata-Toolkit
  - mvn clean install

